# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/project/tadpole_master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/project/tadpole_master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/project/tadpole_master/CMakeFiles /root/project/tadpole_master/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/project/tadpole_master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_lua

# Build rule for target.
test_lua: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lua
.PHONY : test_lua

# fast build rule for target.
test_lua/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lua.dir/build.make CMakeFiles/test_lua.dir/build
.PHONY : test_lua/fast

#=============================================================================
# Target rules for targets named fl_server

# Build rule for target.
fl_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fl_server
.PHONY : fl_server

# fast build rule for target.
fl_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/build
.PHONY : fl_server/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named tadpole

# Build rule for target.
tadpole: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tadpole
.PHONY : tadpole

# fast build rule for target.
tadpole/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/build
.PHONY : tadpole/fast

examples/FLServer.o: examples/FLServer.cc.o

.PHONY : examples/FLServer.o

# target to build an object file
examples/FLServer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/examples/FLServer.cc.o
.PHONY : examples/FLServer.cc.o

examples/FLServer.i: examples/FLServer.cc.i

.PHONY : examples/FLServer.i

# target to preprocess a source file
examples/FLServer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/examples/FLServer.cc.i
.PHONY : examples/FLServer.cc.i

examples/FLServer.s: examples/FLServer.cc.s

.PHONY : examples/FLServer.s

# target to generate assembly for a file
examples/FLServer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/examples/FLServer.cc.s
.PHONY : examples/FLServer.cc.s

examples/FightLandlord/Random.o: examples/FightLandlord/Random.cc.o

.PHONY : examples/FightLandlord/Random.o

# target to build an object file
examples/FightLandlord/Random.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Random.cc.o
.PHONY : examples/FightLandlord/Random.cc.o

examples/FightLandlord/Random.i: examples/FightLandlord/Random.cc.i

.PHONY : examples/FightLandlord/Random.i

# target to preprocess a source file
examples/FightLandlord/Random.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Random.cc.i
.PHONY : examples/FightLandlord/Random.cc.i

examples/FightLandlord/Random.s: examples/FightLandlord/Random.cc.s

.PHONY : examples/FightLandlord/Random.s

# target to generate assembly for a file
examples/FightLandlord/Random.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Random.cc.s
.PHONY : examples/FightLandlord/Random.cc.s

examples/FightLandlord/Room.o: examples/FightLandlord/Room.cc.o

.PHONY : examples/FightLandlord/Room.o

# target to build an object file
examples/FightLandlord/Room.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Room.cc.o
.PHONY : examples/FightLandlord/Room.cc.o

examples/FightLandlord/Room.i: examples/FightLandlord/Room.cc.i

.PHONY : examples/FightLandlord/Room.i

# target to preprocess a source file
examples/FightLandlord/Room.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Room.cc.i
.PHONY : examples/FightLandlord/Room.cc.i

examples/FightLandlord/Room.s: examples/FightLandlord/Room.cc.s

.PHONY : examples/FightLandlord/Room.s

# target to generate assembly for a file
examples/FightLandlord/Room.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Room.cc.s
.PHONY : examples/FightLandlord/Room.cc.s

examples/FightLandlord/protocal.o: examples/FightLandlord/protocal.cc.o

.PHONY : examples/FightLandlord/protocal.o

# target to build an object file
examples/FightLandlord/protocal.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/protocal.cc.o
.PHONY : examples/FightLandlord/protocal.cc.o

examples/FightLandlord/protocal.i: examples/FightLandlord/protocal.cc.i

.PHONY : examples/FightLandlord/protocal.i

# target to preprocess a source file
examples/FightLandlord/protocal.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/protocal.cc.i
.PHONY : examples/FightLandlord/protocal.cc.i

examples/FightLandlord/protocal.s: examples/FightLandlord/protocal.cc.s

.PHONY : examples/FightLandlord/protocal.s

# target to generate assembly for a file
examples/FightLandlord/protocal.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/protocal.cc.s
.PHONY : examples/FightLandlord/protocal.cc.s

examples/FightLandlord/ws_session.o: examples/FightLandlord/ws_session.cc.o

.PHONY : examples/FightLandlord/ws_session.o

# target to build an object file
examples/FightLandlord/ws_session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/ws_session.cc.o
.PHONY : examples/FightLandlord/ws_session.cc.o

examples/FightLandlord/ws_session.i: examples/FightLandlord/ws_session.cc.i

.PHONY : examples/FightLandlord/ws_session.i

# target to preprocess a source file
examples/FightLandlord/ws_session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/ws_session.cc.i
.PHONY : examples/FightLandlord/ws_session.cc.i

examples/FightLandlord/ws_session.s: examples/FightLandlord/ws_session.cc.s

.PHONY : examples/FightLandlord/ws_session.s

# target to generate assembly for a file
examples/FightLandlord/ws_session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/ws_session.cc.s
.PHONY : examples/FightLandlord/ws_session.cc.s

src/address.o: src/address.cc.o

.PHONY : src/address.o

# target to build an object file
src/address.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/address.cc.o
.PHONY : src/address.cc.o

src/address.i: src/address.cc.i

.PHONY : src/address.i

# target to preprocess a source file
src/address.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/address.cc.i
.PHONY : src/address.cc.i

src/address.s: src/address.cc.s

.PHONY : src/address.s

# target to generate assembly for a file
src/address.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/address.cc.s
.PHONY : src/address.cc.s

src/bytearray.o: src/bytearray.cc.o

.PHONY : src/bytearray.o

# target to build an object file
src/bytearray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/bytearray.cc.o
.PHONY : src/bytearray.cc.o

src/bytearray.i: src/bytearray.cc.i

.PHONY : src/bytearray.i

# target to preprocess a source file
src/bytearray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/bytearray.cc.i
.PHONY : src/bytearray.cc.i

src/bytearray.s: src/bytearray.cc.s

.PHONY : src/bytearray.s

# target to generate assembly for a file
src/bytearray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/bytearray.cc.s
.PHONY : src/bytearray.cc.s

src/config.o: src/config.cc.o

.PHONY : src/config.o

# target to build an object file
src/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/config.cc.o
.PHONY : src/config.cc.o

src/config.i: src/config.cc.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/config.cc.i
.PHONY : src/config.cc.i

src/config.s: src/config.cc.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/config.cc.s
.PHONY : src/config.cc.s

src/fdmanager.o: src/fdmanager.cc.o

.PHONY : src/fdmanager.o

# target to build an object file
src/fdmanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fdmanager.cc.o
.PHONY : src/fdmanager.cc.o

src/fdmanager.i: src/fdmanager.cc.i

.PHONY : src/fdmanager.i

# target to preprocess a source file
src/fdmanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fdmanager.cc.i
.PHONY : src/fdmanager.cc.i

src/fdmanager.s: src/fdmanager.cc.s

.PHONY : src/fdmanager.s

# target to generate assembly for a file
src/fdmanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fdmanager.cc.s
.PHONY : src/fdmanager.cc.s

src/fiber.o: src/fiber.cc.o

.PHONY : src/fiber.o

# target to build an object file
src/fiber.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fiber.cc.o
.PHONY : src/fiber.cc.o

src/fiber.i: src/fiber.cc.i

.PHONY : src/fiber.i

# target to preprocess a source file
src/fiber.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fiber.cc.i
.PHONY : src/fiber.cc.i

src/fiber.s: src/fiber.cc.s

.PHONY : src/fiber.s

# target to generate assembly for a file
src/fiber.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fiber.cc.s
.PHONY : src/fiber.cc.s

src/hook.o: src/hook.cc.o

.PHONY : src/hook.o

# target to build an object file
src/hook.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/hook.cc.o
.PHONY : src/hook.cc.o

src/hook.i: src/hook.cc.i

.PHONY : src/hook.i

# target to preprocess a source file
src/hook.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/hook.cc.i
.PHONY : src/hook.cc.i

src/hook.s: src/hook.cc.s

.PHONY : src/hook.s

# target to generate assembly for a file
src/hook.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/hook.cc.s
.PHONY : src/hook.cc.s

src/http/http11_parser.o: src/http/http11_parser.cc.o

.PHONY : src/http/http11_parser.o

# target to build an object file
src/http/http11_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http11_parser.cc.o
.PHONY : src/http/http11_parser.cc.o

src/http/http11_parser.i: src/http/http11_parser.cc.i

.PHONY : src/http/http11_parser.i

# target to preprocess a source file
src/http/http11_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http11_parser.cc.i
.PHONY : src/http/http11_parser.cc.i

src/http/http11_parser.s: src/http/http11_parser.cc.s

.PHONY : src/http/http11_parser.s

# target to generate assembly for a file
src/http/http11_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http11_parser.cc.s
.PHONY : src/http/http11_parser.cc.s

src/http/http_request.o: src/http/http_request.cc.o

.PHONY : src/http/http_request.o

# target to build an object file
src/http/http_request.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_request.cc.o
.PHONY : src/http/http_request.cc.o

src/http/http_request.i: src/http/http_request.cc.i

.PHONY : src/http/http_request.i

# target to preprocess a source file
src/http/http_request.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_request.cc.i
.PHONY : src/http/http_request.cc.i

src/http/http_request.s: src/http/http_request.cc.s

.PHONY : src/http/http_request.s

# target to generate assembly for a file
src/http/http_request.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_request.cc.s
.PHONY : src/http/http_request.cc.s

src/http/http_responce.o: src/http/http_responce.cc.o

.PHONY : src/http/http_responce.o

# target to build an object file
src/http/http_responce.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_responce.cc.o
.PHONY : src/http/http_responce.cc.o

src/http/http_responce.i: src/http/http_responce.cc.i

.PHONY : src/http/http_responce.i

# target to preprocess a source file
src/http/http_responce.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_responce.cc.i
.PHONY : src/http/http_responce.cc.i

src/http/http_responce.s: src/http/http_responce.cc.s

.PHONY : src/http/http_responce.s

# target to generate assembly for a file
src/http/http_responce.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_responce.cc.s
.PHONY : src/http/http_responce.cc.s

src/http/http_servlet.o: src/http/http_servlet.cc.o

.PHONY : src/http/http_servlet.o

# target to build an object file
src/http/http_servlet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_servlet.cc.o
.PHONY : src/http/http_servlet.cc.o

src/http/http_servlet.i: src/http/http_servlet.cc.i

.PHONY : src/http/http_servlet.i

# target to preprocess a source file
src/http/http_servlet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_servlet.cc.i
.PHONY : src/http/http_servlet.cc.i

src/http/http_servlet.s: src/http/http_servlet.cc.s

.PHONY : src/http/http_servlet.s

# target to generate assembly for a file
src/http/http_servlet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_servlet.cc.s
.PHONY : src/http/http_servlet.cc.s

src/http/http_session.o: src/http/http_session.cc.o

.PHONY : src/http/http_session.o

# target to build an object file
src/http/http_session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_session.cc.o
.PHONY : src/http/http_session.cc.o

src/http/http_session.i: src/http/http_session.cc.i

.PHONY : src/http/http_session.i

# target to preprocess a source file
src/http/http_session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_session.cc.i
.PHONY : src/http/http_session.cc.i

src/http/http_session.s: src/http/http_session.cc.s

.PHONY : src/http/http_session.s

# target to generate assembly for a file
src/http/http_session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_session.cc.s
.PHONY : src/http/http_session.cc.s

src/http/httpclient_parser.o: src/http/httpclient_parser.cc.o

.PHONY : src/http/httpclient_parser.o

# target to build an object file
src/http/httpclient_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/httpclient_parser.cc.o
.PHONY : src/http/httpclient_parser.cc.o

src/http/httpclient_parser.i: src/http/httpclient_parser.cc.i

.PHONY : src/http/httpclient_parser.i

# target to preprocess a source file
src/http/httpclient_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/httpclient_parser.cc.i
.PHONY : src/http/httpclient_parser.cc.i

src/http/httpclient_parser.s: src/http/httpclient_parser.cc.s

.PHONY : src/http/httpclient_parser.s

# target to generate assembly for a file
src/http/httpclient_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/httpclient_parser.cc.s
.PHONY : src/http/httpclient_parser.cc.s

src/iomanager.o: src/iomanager.cc.o

.PHONY : src/iomanager.o

# target to build an object file
src/iomanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/iomanager.cc.o
.PHONY : src/iomanager.cc.o

src/iomanager.i: src/iomanager.cc.i

.PHONY : src/iomanager.i

# target to preprocess a source file
src/iomanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/iomanager.cc.i
.PHONY : src/iomanager.cc.i

src/iomanager.s: src/iomanager.cc.s

.PHONY : src/iomanager.s

# target to generate assembly for a file
src/iomanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/iomanager.cc.s
.PHONY : src/iomanager.cc.s

src/log.o: src/log.cc.o

.PHONY : src/log.o

# target to build an object file
src/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/log.cc.o
.PHONY : src/log.cc.o

src/log.i: src/log.cc.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/log.cc.i
.PHONY : src/log.cc.i

src/log.s: src/log.cc.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/log.cc.s
.PHONY : src/log.cc.s

src/luaregister.o: src/luaregister.cc.o

.PHONY : src/luaregister.o

# target to build an object file
src/luaregister.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/luaregister.cc.o
.PHONY : src/luaregister.cc.o

src/luaregister.i: src/luaregister.cc.i

.PHONY : src/luaregister.i

# target to preprocess a source file
src/luaregister.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/luaregister.cc.i
.PHONY : src/luaregister.cc.i

src/luaregister.s: src/luaregister.cc.s

.PHONY : src/luaregister.s

# target to generate assembly for a file
src/luaregister.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/luaregister.cc.s
.PHONY : src/luaregister.cc.s

src/luastack.o: src/luastack.cc.o

.PHONY : src/luastack.o

# target to build an object file
src/luastack.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/luastack.cc.o
.PHONY : src/luastack.cc.o

src/luastack.i: src/luastack.cc.i

.PHONY : src/luastack.i

# target to preprocess a source file
src/luastack.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/luastack.cc.i
.PHONY : src/luastack.cc.i

src/luastack.s: src/luastack.cc.s

.PHONY : src/luastack.s

# target to generate assembly for a file
src/luastack.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/luastack.cc.s
.PHONY : src/luastack.cc.s

src/mutex.o: src/mutex.cc.o

.PHONY : src/mutex.o

# target to build an object file
src/mutex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/mutex.cc.o
.PHONY : src/mutex.cc.o

src/mutex.i: src/mutex.cc.i

.PHONY : src/mutex.i

# target to preprocess a source file
src/mutex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/mutex.cc.i
.PHONY : src/mutex.cc.i

src/mutex.s: src/mutex.cc.s

.PHONY : src/mutex.s

# target to generate assembly for a file
src/mutex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/mutex.cc.s
.PHONY : src/mutex.cc.s

src/scheduler.o: src/scheduler.cc.o

.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/scheduler.cc.o
.PHONY : src/scheduler.cc.o

src/scheduler.i: src/scheduler.cc.i

.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/scheduler.cc.i
.PHONY : src/scheduler.cc.i

src/scheduler.s: src/scheduler.cc.s

.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/scheduler.cc.s
.PHONY : src/scheduler.cc.s

src/socket.o: src/socket.cc.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/socket.cc.o
.PHONY : src/socket.cc.o

src/socket.i: src/socket.cc.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/socket.cc.i
.PHONY : src/socket.cc.i

src/socket.s: src/socket.cc.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/socket.cc.s
.PHONY : src/socket.cc.s

src/tcpserver.o: src/tcpserver.cc.o

.PHONY : src/tcpserver.o

# target to build an object file
src/tcpserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/tcpserver.cc.o
.PHONY : src/tcpserver.cc.o

src/tcpserver.i: src/tcpserver.cc.i

.PHONY : src/tcpserver.i

# target to preprocess a source file
src/tcpserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/tcpserver.cc.i
.PHONY : src/tcpserver.cc.i

src/tcpserver.s: src/tcpserver.cc.s

.PHONY : src/tcpserver.s

# target to generate assembly for a file
src/tcpserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/tcpserver.cc.s
.PHONY : src/tcpserver.cc.s

src/thread.o: src/thread.cc.o

.PHONY : src/thread.o

# target to build an object file
src/thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/thread.cc.o
.PHONY : src/thread.cc.o

src/thread.i: src/thread.cc.i

.PHONY : src/thread.i

# target to preprocess a source file
src/thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/thread.cc.i
.PHONY : src/thread.cc.i

src/thread.s: src/thread.cc.s

.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/thread.cc.s
.PHONY : src/thread.cc.s

src/timer.o: src/timer.cc.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/timer.cc.o
.PHONY : src/timer.cc.o

src/timer.i: src/timer.cc.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/timer.cc.i
.PHONY : src/timer.cc.i

src/timer.s: src/timer.cc.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/timer.cc.s
.PHONY : src/timer.cc.s

src/util.o: src/util.cc.o

.PHONY : src/util.o

# target to build an object file
src/util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/util.cc.o
.PHONY : src/util.cc.o

src/util.i: src/util.cc.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/util.cc.i
.PHONY : src/util.cc.i

src/util.s: src/util.cc.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/util.cc.s
.PHONY : src/util.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_lua.o: tests/test_lua.cc.o

.PHONY : tests/test_lua.o

# target to build an object file
tests/test_lua.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lua.dir/build.make CMakeFiles/test_lua.dir/tests/test_lua.cc.o
.PHONY : tests/test_lua.cc.o

tests/test_lua.i: tests/test_lua.cc.i

.PHONY : tests/test_lua.i

# target to preprocess a source file
tests/test_lua.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lua.dir/build.make CMakeFiles/test_lua.dir/tests/test_lua.cc.i
.PHONY : tests/test_lua.cc.i

tests/test_lua.s: tests/test_lua.cc.s

.PHONY : tests/test_lua.s

# target to generate assembly for a file
tests/test_lua.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lua.dir/build.make CMakeFiles/test_lua.dir/tests/test_lua.cc.s
.PHONY : tests/test_lua.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_lua"
	@echo "... fl_server"
	@echo "... test_iomanager"
	@echo "... tadpole"
	@echo "... examples/FLServer.o"
	@echo "... examples/FLServer.i"
	@echo "... examples/FLServer.s"
	@echo "... examples/FightLandlord/Random.o"
	@echo "... examples/FightLandlord/Random.i"
	@echo "... examples/FightLandlord/Random.s"
	@echo "... examples/FightLandlord/Room.o"
	@echo "... examples/FightLandlord/Room.i"
	@echo "... examples/FightLandlord/Room.s"
	@echo "... examples/FightLandlord/protocal.o"
	@echo "... examples/FightLandlord/protocal.i"
	@echo "... examples/FightLandlord/protocal.s"
	@echo "... examples/FightLandlord/ws_session.o"
	@echo "... examples/FightLandlord/ws_session.i"
	@echo "... examples/FightLandlord/ws_session.s"
	@echo "... src/address.o"
	@echo "... src/address.i"
	@echo "... src/address.s"
	@echo "... src/bytearray.o"
	@echo "... src/bytearray.i"
	@echo "... src/bytearray.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/fdmanager.o"
	@echo "... src/fdmanager.i"
	@echo "... src/fdmanager.s"
	@echo "... src/fiber.o"
	@echo "... src/fiber.i"
	@echo "... src/fiber.s"
	@echo "... src/hook.o"
	@echo "... src/hook.i"
	@echo "... src/hook.s"
	@echo "... src/http/http11_parser.o"
	@echo "... src/http/http11_parser.i"
	@echo "... src/http/http11_parser.s"
	@echo "... src/http/http_request.o"
	@echo "... src/http/http_request.i"
	@echo "... src/http/http_request.s"
	@echo "... src/http/http_responce.o"
	@echo "... src/http/http_responce.i"
	@echo "... src/http/http_responce.s"
	@echo "... src/http/http_servlet.o"
	@echo "... src/http/http_servlet.i"
	@echo "... src/http/http_servlet.s"
	@echo "... src/http/http_session.o"
	@echo "... src/http/http_session.i"
	@echo "... src/http/http_session.s"
	@echo "... src/http/httpclient_parser.o"
	@echo "... src/http/httpclient_parser.i"
	@echo "... src/http/httpclient_parser.s"
	@echo "... src/iomanager.o"
	@echo "... src/iomanager.i"
	@echo "... src/iomanager.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/luaregister.o"
	@echo "... src/luaregister.i"
	@echo "... src/luaregister.s"
	@echo "... src/luastack.o"
	@echo "... src/luastack.i"
	@echo "... src/luastack.s"
	@echo "... src/mutex.o"
	@echo "... src/mutex.i"
	@echo "... src/mutex.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/tcpserver.o"
	@echo "... src/tcpserver.i"
	@echo "... src/tcpserver.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_lua.o"
	@echo "... tests/test_lua.i"
	@echo "... tests/test_lua.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

