# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/project/tadpole_master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/project/tadpole_master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/project/tadpole_master/CMakeFiles /root/project/tadpole_master/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/project/tadpole_master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_httpserver

# Build rule for target.
test_httpserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_httpserver
.PHONY : test_httpserver

# fast build rule for target.
test_httpserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpserver.dir/build.make CMakeFiles/test_httpserver.dir/build
.PHONY : test_httpserver/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_yaml

# Build rule for target.
test_yaml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_yaml
.PHONY : test_yaml

# fast build rule for target.
test_yaml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_yaml.dir/build.make CMakeFiles/test_yaml.dir/build
.PHONY : test_yaml/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_httpsession

# Build rule for target.
test_httpsession: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_httpsession
.PHONY : test_httpsession

# fast build rule for target.
test_httpsession/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpsession.dir/build.make CMakeFiles/test_httpsession.dir/build
.PHONY : test_httpsession/fast

#=============================================================================
# Target rules for targets named test_log

# Build rule for target.
test_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_log
.PHONY : test_log

# fast build rule for target.
test_log/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/build
.PHONY : test_log/fast

#=============================================================================
# Target rules for targets named test_parser

# Build rule for target.
test_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_parser
.PHONY : test_parser

# fast build rule for target.
test_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/build
.PHONY : test_parser/fast

#=============================================================================
# Target rules for targets named test_addr

# Build rule for target.
test_addr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_addr
.PHONY : test_addr

# fast build rule for target.
test_addr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/build
.PHONY : test_addr/fast

#=============================================================================
# Target rules for targets named tadpole

# Build rule for target.
tadpole: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tadpole
.PHONY : tadpole

# fast build rule for target.
tadpole/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/build
.PHONY : tadpole/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_tcpserver

# Build rule for target.
test_tcpserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tcpserver
.PHONY : test_tcpserver

# fast build rule for target.
test_tcpserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/build
.PHONY : test_tcpserver/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_httprequest

# Build rule for target.
test_httprequest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_httprequest
.PHONY : test_httprequest

# fast build rule for target.
test_httprequest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httprequest.dir/build.make CMakeFiles/test_httprequest.dir/build
.PHONY : test_httprequest/fast

#=============================================================================
# Target rules for targets named test_httpresponce

# Build rule for target.
test_httpresponce: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_httpresponce
.PHONY : test_httpresponce

# fast build rule for target.
test_httpresponce/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpresponce.dir/build.make CMakeFiles/test_httpresponce.dir/build
.PHONY : test_httpresponce/fast

#=============================================================================
# Target rules for targets named test_random

# Build rule for target.
test_random: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_random
.PHONY : test_random

# fast build rule for target.
test_random/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_random.dir/build.make CMakeFiles/test_random.dir/build
.PHONY : test_random/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named fl_server

# Build rule for target.
fl_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fl_server
.PHONY : fl_server

# fast build rule for target.
fl_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/build
.PHONY : fl_server/fast

examples/FLServer.o: examples/FLServer.cc.o

.PHONY : examples/FLServer.o

# target to build an object file
examples/FLServer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/examples/FLServer.cc.o
.PHONY : examples/FLServer.cc.o

examples/FLServer.i: examples/FLServer.cc.i

.PHONY : examples/FLServer.i

# target to preprocess a source file
examples/FLServer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/examples/FLServer.cc.i
.PHONY : examples/FLServer.cc.i

examples/FLServer.s: examples/FLServer.cc.s

.PHONY : examples/FLServer.s

# target to generate assembly for a file
examples/FLServer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fl_server.dir/build.make CMakeFiles/fl_server.dir/examples/FLServer.cc.s
.PHONY : examples/FLServer.cc.s

examples/FightLandlord/Random.o: examples/FightLandlord/Random.cc.o

.PHONY : examples/FightLandlord/Random.o

# target to build an object file
examples/FightLandlord/Random.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Random.cc.o
.PHONY : examples/FightLandlord/Random.cc.o

examples/FightLandlord/Random.i: examples/FightLandlord/Random.cc.i

.PHONY : examples/FightLandlord/Random.i

# target to preprocess a source file
examples/FightLandlord/Random.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Random.cc.i
.PHONY : examples/FightLandlord/Random.cc.i

examples/FightLandlord/Random.s: examples/FightLandlord/Random.cc.s

.PHONY : examples/FightLandlord/Random.s

# target to generate assembly for a file
examples/FightLandlord/Random.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Random.cc.s
.PHONY : examples/FightLandlord/Random.cc.s

examples/FightLandlord/Room.o: examples/FightLandlord/Room.cc.o

.PHONY : examples/FightLandlord/Room.o

# target to build an object file
examples/FightLandlord/Room.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Room.cc.o
.PHONY : examples/FightLandlord/Room.cc.o

examples/FightLandlord/Room.i: examples/FightLandlord/Room.cc.i

.PHONY : examples/FightLandlord/Room.i

# target to preprocess a source file
examples/FightLandlord/Room.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Room.cc.i
.PHONY : examples/FightLandlord/Room.cc.i

examples/FightLandlord/Room.s: examples/FightLandlord/Room.cc.s

.PHONY : examples/FightLandlord/Room.s

# target to generate assembly for a file
examples/FightLandlord/Room.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/Room.cc.s
.PHONY : examples/FightLandlord/Room.cc.s

examples/FightLandlord/protocal.o: examples/FightLandlord/protocal.cc.o

.PHONY : examples/FightLandlord/protocal.o

# target to build an object file
examples/FightLandlord/protocal.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/protocal.cc.o
.PHONY : examples/FightLandlord/protocal.cc.o

examples/FightLandlord/protocal.i: examples/FightLandlord/protocal.cc.i

.PHONY : examples/FightLandlord/protocal.i

# target to preprocess a source file
examples/FightLandlord/protocal.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/protocal.cc.i
.PHONY : examples/FightLandlord/protocal.cc.i

examples/FightLandlord/protocal.s: examples/FightLandlord/protocal.cc.s

.PHONY : examples/FightLandlord/protocal.s

# target to generate assembly for a file
examples/FightLandlord/protocal.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/protocal.cc.s
.PHONY : examples/FightLandlord/protocal.cc.s

examples/FightLandlord/ws_session.o: examples/FightLandlord/ws_session.cc.o

.PHONY : examples/FightLandlord/ws_session.o

# target to build an object file
examples/FightLandlord/ws_session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/ws_session.cc.o
.PHONY : examples/FightLandlord/ws_session.cc.o

examples/FightLandlord/ws_session.i: examples/FightLandlord/ws_session.cc.i

.PHONY : examples/FightLandlord/ws_session.i

# target to preprocess a source file
examples/FightLandlord/ws_session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/ws_session.cc.i
.PHONY : examples/FightLandlord/ws_session.cc.i

examples/FightLandlord/ws_session.s: examples/FightLandlord/ws_session.cc.s

.PHONY : examples/FightLandlord/ws_session.s

# target to generate assembly for a file
examples/FightLandlord/ws_session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/examples/FightLandlord/ws_session.cc.s
.PHONY : examples/FightLandlord/ws_session.cc.s

examples/echoServer.o: examples/echoServer.cc.o

.PHONY : examples/echoServer.o

# target to build an object file
examples/echoServer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echoServer.cc.o
.PHONY : examples/echoServer.cc.o

examples/echoServer.i: examples/echoServer.cc.i

.PHONY : examples/echoServer.i

# target to preprocess a source file
examples/echoServer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echoServer.cc.i
.PHONY : examples/echoServer.cc.i

examples/echoServer.s: examples/echoServer.cc.s

.PHONY : examples/echoServer.s

# target to generate assembly for a file
examples/echoServer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echoServer.cc.s
.PHONY : examples/echoServer.cc.s

src/address.o: src/address.cc.o

.PHONY : src/address.o

# target to build an object file
src/address.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/address.cc.o
.PHONY : src/address.cc.o

src/address.i: src/address.cc.i

.PHONY : src/address.i

# target to preprocess a source file
src/address.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/address.cc.i
.PHONY : src/address.cc.i

src/address.s: src/address.cc.s

.PHONY : src/address.s

# target to generate assembly for a file
src/address.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/address.cc.s
.PHONY : src/address.cc.s

src/bytearray.o: src/bytearray.cc.o

.PHONY : src/bytearray.o

# target to build an object file
src/bytearray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/bytearray.cc.o
.PHONY : src/bytearray.cc.o

src/bytearray.i: src/bytearray.cc.i

.PHONY : src/bytearray.i

# target to preprocess a source file
src/bytearray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/bytearray.cc.i
.PHONY : src/bytearray.cc.i

src/bytearray.s: src/bytearray.cc.s

.PHONY : src/bytearray.s

# target to generate assembly for a file
src/bytearray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/bytearray.cc.s
.PHONY : src/bytearray.cc.s

src/config.o: src/config.cc.o

.PHONY : src/config.o

# target to build an object file
src/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/config.cc.o
.PHONY : src/config.cc.o

src/config.i: src/config.cc.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/config.cc.i
.PHONY : src/config.cc.i

src/config.s: src/config.cc.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/config.cc.s
.PHONY : src/config.cc.s

src/fdmanager.o: src/fdmanager.cc.o

.PHONY : src/fdmanager.o

# target to build an object file
src/fdmanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fdmanager.cc.o
.PHONY : src/fdmanager.cc.o

src/fdmanager.i: src/fdmanager.cc.i

.PHONY : src/fdmanager.i

# target to preprocess a source file
src/fdmanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fdmanager.cc.i
.PHONY : src/fdmanager.cc.i

src/fdmanager.s: src/fdmanager.cc.s

.PHONY : src/fdmanager.s

# target to generate assembly for a file
src/fdmanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fdmanager.cc.s
.PHONY : src/fdmanager.cc.s

src/fiber.o: src/fiber.cc.o

.PHONY : src/fiber.o

# target to build an object file
src/fiber.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fiber.cc.o
.PHONY : src/fiber.cc.o

src/fiber.i: src/fiber.cc.i

.PHONY : src/fiber.i

# target to preprocess a source file
src/fiber.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fiber.cc.i
.PHONY : src/fiber.cc.i

src/fiber.s: src/fiber.cc.s

.PHONY : src/fiber.s

# target to generate assembly for a file
src/fiber.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/fiber.cc.s
.PHONY : src/fiber.cc.s

src/hook.o: src/hook.cc.o

.PHONY : src/hook.o

# target to build an object file
src/hook.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/hook.cc.o
.PHONY : src/hook.cc.o

src/hook.i: src/hook.cc.i

.PHONY : src/hook.i

# target to preprocess a source file
src/hook.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/hook.cc.i
.PHONY : src/hook.cc.i

src/hook.s: src/hook.cc.s

.PHONY : src/hook.s

# target to generate assembly for a file
src/hook.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/hook.cc.s
.PHONY : src/hook.cc.s

src/http/http11_parser.o: src/http/http11_parser.cc.o

.PHONY : src/http/http11_parser.o

# target to build an object file
src/http/http11_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http11_parser.cc.o
.PHONY : src/http/http11_parser.cc.o

src/http/http11_parser.i: src/http/http11_parser.cc.i

.PHONY : src/http/http11_parser.i

# target to preprocess a source file
src/http/http11_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http11_parser.cc.i
.PHONY : src/http/http11_parser.cc.i

src/http/http11_parser.s: src/http/http11_parser.cc.s

.PHONY : src/http/http11_parser.s

# target to generate assembly for a file
src/http/http11_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http11_parser.cc.s
.PHONY : src/http/http11_parser.cc.s

src/http/http_request.o: src/http/http_request.cc.o

.PHONY : src/http/http_request.o

# target to build an object file
src/http/http_request.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_request.cc.o
.PHONY : src/http/http_request.cc.o

src/http/http_request.i: src/http/http_request.cc.i

.PHONY : src/http/http_request.i

# target to preprocess a source file
src/http/http_request.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_request.cc.i
.PHONY : src/http/http_request.cc.i

src/http/http_request.s: src/http/http_request.cc.s

.PHONY : src/http/http_request.s

# target to generate assembly for a file
src/http/http_request.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_request.cc.s
.PHONY : src/http/http_request.cc.s

src/http/http_responce.o: src/http/http_responce.cc.o

.PHONY : src/http/http_responce.o

# target to build an object file
src/http/http_responce.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_responce.cc.o
.PHONY : src/http/http_responce.cc.o

src/http/http_responce.i: src/http/http_responce.cc.i

.PHONY : src/http/http_responce.i

# target to preprocess a source file
src/http/http_responce.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_responce.cc.i
.PHONY : src/http/http_responce.cc.i

src/http/http_responce.s: src/http/http_responce.cc.s

.PHONY : src/http/http_responce.s

# target to generate assembly for a file
src/http/http_responce.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_responce.cc.s
.PHONY : src/http/http_responce.cc.s

src/http/http_servlet.o: src/http/http_servlet.cc.o

.PHONY : src/http/http_servlet.o

# target to build an object file
src/http/http_servlet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_servlet.cc.o
.PHONY : src/http/http_servlet.cc.o

src/http/http_servlet.i: src/http/http_servlet.cc.i

.PHONY : src/http/http_servlet.i

# target to preprocess a source file
src/http/http_servlet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_servlet.cc.i
.PHONY : src/http/http_servlet.cc.i

src/http/http_servlet.s: src/http/http_servlet.cc.s

.PHONY : src/http/http_servlet.s

# target to generate assembly for a file
src/http/http_servlet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_servlet.cc.s
.PHONY : src/http/http_servlet.cc.s

src/http/http_session.o: src/http/http_session.cc.o

.PHONY : src/http/http_session.o

# target to build an object file
src/http/http_session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_session.cc.o
.PHONY : src/http/http_session.cc.o

src/http/http_session.i: src/http/http_session.cc.i

.PHONY : src/http/http_session.i

# target to preprocess a source file
src/http/http_session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_session.cc.i
.PHONY : src/http/http_session.cc.i

src/http/http_session.s: src/http/http_session.cc.s

.PHONY : src/http/http_session.s

# target to generate assembly for a file
src/http/http_session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/http_session.cc.s
.PHONY : src/http/http_session.cc.s

src/http/httpclient_parser.o: src/http/httpclient_parser.cc.o

.PHONY : src/http/httpclient_parser.o

# target to build an object file
src/http/httpclient_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/httpclient_parser.cc.o
.PHONY : src/http/httpclient_parser.cc.o

src/http/httpclient_parser.i: src/http/httpclient_parser.cc.i

.PHONY : src/http/httpclient_parser.i

# target to preprocess a source file
src/http/httpclient_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/httpclient_parser.cc.i
.PHONY : src/http/httpclient_parser.cc.i

src/http/httpclient_parser.s: src/http/httpclient_parser.cc.s

.PHONY : src/http/httpclient_parser.s

# target to generate assembly for a file
src/http/httpclient_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/http/httpclient_parser.cc.s
.PHONY : src/http/httpclient_parser.cc.s

src/iomanager.o: src/iomanager.cc.o

.PHONY : src/iomanager.o

# target to build an object file
src/iomanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/iomanager.cc.o
.PHONY : src/iomanager.cc.o

src/iomanager.i: src/iomanager.cc.i

.PHONY : src/iomanager.i

# target to preprocess a source file
src/iomanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/iomanager.cc.i
.PHONY : src/iomanager.cc.i

src/iomanager.s: src/iomanager.cc.s

.PHONY : src/iomanager.s

# target to generate assembly for a file
src/iomanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/iomanager.cc.s
.PHONY : src/iomanager.cc.s

src/log.o: src/log.cc.o

.PHONY : src/log.o

# target to build an object file
src/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/log.cc.o
.PHONY : src/log.cc.o

src/log.i: src/log.cc.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/log.cc.i
.PHONY : src/log.cc.i

src/log.s: src/log.cc.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/log.cc.s
.PHONY : src/log.cc.s

src/mutex.o: src/mutex.cc.o

.PHONY : src/mutex.o

# target to build an object file
src/mutex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/mutex.cc.o
.PHONY : src/mutex.cc.o

src/mutex.i: src/mutex.cc.i

.PHONY : src/mutex.i

# target to preprocess a source file
src/mutex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/mutex.cc.i
.PHONY : src/mutex.cc.i

src/mutex.s: src/mutex.cc.s

.PHONY : src/mutex.s

# target to generate assembly for a file
src/mutex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/mutex.cc.s
.PHONY : src/mutex.cc.s

src/scheduler.o: src/scheduler.cc.o

.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/scheduler.cc.o
.PHONY : src/scheduler.cc.o

src/scheduler.i: src/scheduler.cc.i

.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/scheduler.cc.i
.PHONY : src/scheduler.cc.i

src/scheduler.s: src/scheduler.cc.s

.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/scheduler.cc.s
.PHONY : src/scheduler.cc.s

src/socket.o: src/socket.cc.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/socket.cc.o
.PHONY : src/socket.cc.o

src/socket.i: src/socket.cc.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/socket.cc.i
.PHONY : src/socket.cc.i

src/socket.s: src/socket.cc.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/socket.cc.s
.PHONY : src/socket.cc.s

src/tcpserver.o: src/tcpserver.cc.o

.PHONY : src/tcpserver.o

# target to build an object file
src/tcpserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/tcpserver.cc.o
.PHONY : src/tcpserver.cc.o

src/tcpserver.i: src/tcpserver.cc.i

.PHONY : src/tcpserver.i

# target to preprocess a source file
src/tcpserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/tcpserver.cc.i
.PHONY : src/tcpserver.cc.i

src/tcpserver.s: src/tcpserver.cc.s

.PHONY : src/tcpserver.s

# target to generate assembly for a file
src/tcpserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/tcpserver.cc.s
.PHONY : src/tcpserver.cc.s

src/thread.o: src/thread.cc.o

.PHONY : src/thread.o

# target to build an object file
src/thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/thread.cc.o
.PHONY : src/thread.cc.o

src/thread.i: src/thread.cc.i

.PHONY : src/thread.i

# target to preprocess a source file
src/thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/thread.cc.i
.PHONY : src/thread.cc.i

src/thread.s: src/thread.cc.s

.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/thread.cc.s
.PHONY : src/thread.cc.s

src/timer.o: src/timer.cc.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/timer.cc.o
.PHONY : src/timer.cc.o

src/timer.i: src/timer.cc.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/timer.cc.i
.PHONY : src/timer.cc.i

src/timer.s: src/timer.cc.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/timer.cc.s
.PHONY : src/timer.cc.s

src/util.o: src/util.cc.o

.PHONY : src/util.o

# target to build an object file
src/util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/util.cc.o
.PHONY : src/util.cc.o

src/util.i: src/util.cc.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/util.cc.i
.PHONY : src/util.cc.i

src/util.s: src/util.cc.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tadpole.dir/build.make CMakeFiles/tadpole.dir/src/util.cc.s
.PHONY : src/util.cc.s

tests/test_addr.o: tests/test_addr.cc.o

.PHONY : tests/test_addr.o

# target to build an object file
tests/test_addr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/tests/test_addr.cc.o
.PHONY : tests/test_addr.cc.o

tests/test_addr.i: tests/test_addr.cc.i

.PHONY : tests/test_addr.i

# target to preprocess a source file
tests/test_addr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/tests/test_addr.cc.i
.PHONY : tests/test_addr.cc.i

tests/test_addr.s: tests/test_addr.cc.s

.PHONY : tests/test_addr.s

# target to generate assembly for a file
tests/test_addr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/tests/test_addr.cc.s
.PHONY : tests/test_addr.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_httprequest.o: tests/test_httprequest.cc.o

.PHONY : tests/test_httprequest.o

# target to build an object file
tests/test_httprequest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httprequest.dir/build.make CMakeFiles/test_httprequest.dir/tests/test_httprequest.cc.o
.PHONY : tests/test_httprequest.cc.o

tests/test_httprequest.i: tests/test_httprequest.cc.i

.PHONY : tests/test_httprequest.i

# target to preprocess a source file
tests/test_httprequest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httprequest.dir/build.make CMakeFiles/test_httprequest.dir/tests/test_httprequest.cc.i
.PHONY : tests/test_httprequest.cc.i

tests/test_httprequest.s: tests/test_httprequest.cc.s

.PHONY : tests/test_httprequest.s

# target to generate assembly for a file
tests/test_httprequest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httprequest.dir/build.make CMakeFiles/test_httprequest.dir/tests/test_httprequest.cc.s
.PHONY : tests/test_httprequest.cc.s

tests/test_httpresponce.o: tests/test_httpresponce.cc.o

.PHONY : tests/test_httpresponce.o

# target to build an object file
tests/test_httpresponce.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpresponce.dir/build.make CMakeFiles/test_httpresponce.dir/tests/test_httpresponce.cc.o
.PHONY : tests/test_httpresponce.cc.o

tests/test_httpresponce.i: tests/test_httpresponce.cc.i

.PHONY : tests/test_httpresponce.i

# target to preprocess a source file
tests/test_httpresponce.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpresponce.dir/build.make CMakeFiles/test_httpresponce.dir/tests/test_httpresponce.cc.i
.PHONY : tests/test_httpresponce.cc.i

tests/test_httpresponce.s: tests/test_httpresponce.cc.s

.PHONY : tests/test_httpresponce.s

# target to generate assembly for a file
tests/test_httpresponce.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpresponce.dir/build.make CMakeFiles/test_httpresponce.dir/tests/test_httpresponce.cc.s
.PHONY : tests/test_httpresponce.cc.s

tests/test_httpserver.o: tests/test_httpserver.cc.o

.PHONY : tests/test_httpserver.o

# target to build an object file
tests/test_httpserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpserver.dir/build.make CMakeFiles/test_httpserver.dir/tests/test_httpserver.cc.o
.PHONY : tests/test_httpserver.cc.o

tests/test_httpserver.i: tests/test_httpserver.cc.i

.PHONY : tests/test_httpserver.i

# target to preprocess a source file
tests/test_httpserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpserver.dir/build.make CMakeFiles/test_httpserver.dir/tests/test_httpserver.cc.i
.PHONY : tests/test_httpserver.cc.i

tests/test_httpserver.s: tests/test_httpserver.cc.s

.PHONY : tests/test_httpserver.s

# target to generate assembly for a file
tests/test_httpserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpserver.dir/build.make CMakeFiles/test_httpserver.dir/tests/test_httpserver.cc.s
.PHONY : tests/test_httpserver.cc.s

tests/test_httpsession.o: tests/test_httpsession.cc.o

.PHONY : tests/test_httpsession.o

# target to build an object file
tests/test_httpsession.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpsession.dir/build.make CMakeFiles/test_httpsession.dir/tests/test_httpsession.cc.o
.PHONY : tests/test_httpsession.cc.o

tests/test_httpsession.i: tests/test_httpsession.cc.i

.PHONY : tests/test_httpsession.i

# target to preprocess a source file
tests/test_httpsession.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpsession.dir/build.make CMakeFiles/test_httpsession.dir/tests/test_httpsession.cc.i
.PHONY : tests/test_httpsession.cc.i

tests/test_httpsession.s: tests/test_httpsession.cc.s

.PHONY : tests/test_httpsession.s

# target to generate assembly for a file
tests/test_httpsession.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_httpsession.dir/build.make CMakeFiles/test_httpsession.dir/tests/test_httpsession.cc.s
.PHONY : tests/test_httpsession.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_log.o: tests/test_log.cc.o

.PHONY : tests/test_log.o

# target to build an object file
tests/test_log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/tests/test_log.cc.o
.PHONY : tests/test_log.cc.o

tests/test_log.i: tests/test_log.cc.i

.PHONY : tests/test_log.i

# target to preprocess a source file
tests/test_log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/tests/test_log.cc.i
.PHONY : tests/test_log.cc.i

tests/test_log.s: tests/test_log.cc.s

.PHONY : tests/test_log.s

# target to generate assembly for a file
tests/test_log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_log.dir/build.make CMakeFiles/test_log.dir/tests/test_log.cc.s
.PHONY : tests/test_log.cc.s

tests/test_parser.o: tests/test_parser.cc.o

.PHONY : tests/test_parser.o

# target to build an object file
tests/test_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/tests/test_parser.cc.o
.PHONY : tests/test_parser.cc.o

tests/test_parser.i: tests/test_parser.cc.i

.PHONY : tests/test_parser.i

# target to preprocess a source file
tests/test_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/tests/test_parser.cc.i
.PHONY : tests/test_parser.cc.i

tests/test_parser.s: tests/test_parser.cc.s

.PHONY : tests/test_parser.s

# target to generate assembly for a file
tests/test_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/tests/test_parser.cc.s
.PHONY : tests/test_parser.cc.s

tests/test_random.o: tests/test_random.cc.o

.PHONY : tests/test_random.o

# target to build an object file
tests/test_random.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_random.dir/build.make CMakeFiles/test_random.dir/tests/test_random.cc.o
.PHONY : tests/test_random.cc.o

tests/test_random.i: tests/test_random.cc.i

.PHONY : tests/test_random.i

# target to preprocess a source file
tests/test_random.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_random.dir/build.make CMakeFiles/test_random.dir/tests/test_random.cc.i
.PHONY : tests/test_random.cc.i

tests/test_random.s: tests/test_random.cc.s

.PHONY : tests/test_random.s

# target to generate assembly for a file
tests/test_random.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_random.dir/build.make CMakeFiles/test_random.dir/tests/test_random.cc.s
.PHONY : tests/test_random.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_tcpserver.o: tests/test_tcpserver.cc.o

.PHONY : tests/test_tcpserver.o

# target to build an object file
tests/test_tcpserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/tests/test_tcpserver.cc.o
.PHONY : tests/test_tcpserver.cc.o

tests/test_tcpserver.i: tests/test_tcpserver.cc.i

.PHONY : tests/test_tcpserver.i

# target to preprocess a source file
tests/test_tcpserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/tests/test_tcpserver.cc.i
.PHONY : tests/test_tcpserver.cc.i

tests/test_tcpserver.s: tests/test_tcpserver.cc.s

.PHONY : tests/test_tcpserver.s

# target to generate assembly for a file
tests/test_tcpserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/tests/test_tcpserver.cc.s
.PHONY : tests/test_tcpserver.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_yaml.o: tests/test_yaml.cc.o

.PHONY : tests/test_yaml.o

# target to build an object file
tests/test_yaml.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_yaml.dir/build.make CMakeFiles/test_yaml.dir/tests/test_yaml.cc.o
.PHONY : tests/test_yaml.cc.o

tests/test_yaml.i: tests/test_yaml.cc.i

.PHONY : tests/test_yaml.i

# target to preprocess a source file
tests/test_yaml.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_yaml.dir/build.make CMakeFiles/test_yaml.dir/tests/test_yaml.cc.i
.PHONY : tests/test_yaml.cc.i

tests/test_yaml.s: tests/test_yaml.cc.s

.PHONY : tests/test_yaml.s

# target to generate assembly for a file
tests/test_yaml.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_yaml.dir/build.make CMakeFiles/test_yaml.dir/tests/test_yaml.cc.s
.PHONY : tests/test_yaml.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_scheduler"
	@echo "... test_fiber"
	@echo "... test_httpserver"
	@echo "... test_thread"
	@echo "... test_yaml"
	@echo "... test_socket"
	@echo "... test_config"
	@echo "... test_httpsession"
	@echo "... test_log"
	@echo "... test_parser"
	@echo "... test_addr"
	@echo "... tadpole"
	@echo "... edit_cache"
	@echo "... test_bytearray"
	@echo "... test_hook"
	@echo "... test_tcpserver"
	@echo "... echo_server"
	@echo "... test_httprequest"
	@echo "... test_httpresponce"
	@echo "... test_random"
	@echo "... test_iomanager"
	@echo "... fl_server"
	@echo "... examples/FLServer.o"
	@echo "... examples/FLServer.i"
	@echo "... examples/FLServer.s"
	@echo "... examples/FightLandlord/Random.o"
	@echo "... examples/FightLandlord/Random.i"
	@echo "... examples/FightLandlord/Random.s"
	@echo "... examples/FightLandlord/Room.o"
	@echo "... examples/FightLandlord/Room.i"
	@echo "... examples/FightLandlord/Room.s"
	@echo "... examples/FightLandlord/protocal.o"
	@echo "... examples/FightLandlord/protocal.i"
	@echo "... examples/FightLandlord/protocal.s"
	@echo "... examples/FightLandlord/ws_session.o"
	@echo "... examples/FightLandlord/ws_session.i"
	@echo "... examples/FightLandlord/ws_session.s"
	@echo "... examples/echoServer.o"
	@echo "... examples/echoServer.i"
	@echo "... examples/echoServer.s"
	@echo "... src/address.o"
	@echo "... src/address.i"
	@echo "... src/address.s"
	@echo "... src/bytearray.o"
	@echo "... src/bytearray.i"
	@echo "... src/bytearray.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/fdmanager.o"
	@echo "... src/fdmanager.i"
	@echo "... src/fdmanager.s"
	@echo "... src/fiber.o"
	@echo "... src/fiber.i"
	@echo "... src/fiber.s"
	@echo "... src/hook.o"
	@echo "... src/hook.i"
	@echo "... src/hook.s"
	@echo "... src/http/http11_parser.o"
	@echo "... src/http/http11_parser.i"
	@echo "... src/http/http11_parser.s"
	@echo "... src/http/http_request.o"
	@echo "... src/http/http_request.i"
	@echo "... src/http/http_request.s"
	@echo "... src/http/http_responce.o"
	@echo "... src/http/http_responce.i"
	@echo "... src/http/http_responce.s"
	@echo "... src/http/http_servlet.o"
	@echo "... src/http/http_servlet.i"
	@echo "... src/http/http_servlet.s"
	@echo "... src/http/http_session.o"
	@echo "... src/http/http_session.i"
	@echo "... src/http/http_session.s"
	@echo "... src/http/httpclient_parser.o"
	@echo "... src/http/httpclient_parser.i"
	@echo "... src/http/httpclient_parser.s"
	@echo "... src/iomanager.o"
	@echo "... src/iomanager.i"
	@echo "... src/iomanager.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/mutex.o"
	@echo "... src/mutex.i"
	@echo "... src/mutex.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/tcpserver.o"
	@echo "... src/tcpserver.i"
	@echo "... src/tcpserver.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... tests/test_addr.o"
	@echo "... tests/test_addr.i"
	@echo "... tests/test_addr.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_httprequest.o"
	@echo "... tests/test_httprequest.i"
	@echo "... tests/test_httprequest.s"
	@echo "... tests/test_httpresponce.o"
	@echo "... tests/test_httpresponce.i"
	@echo "... tests/test_httpresponce.s"
	@echo "... tests/test_httpserver.o"
	@echo "... tests/test_httpserver.i"
	@echo "... tests/test_httpserver.s"
	@echo "... tests/test_httpsession.o"
	@echo "... tests/test_httpsession.i"
	@echo "... tests/test_httpsession.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_log.o"
	@echo "... tests/test_log.i"
	@echo "... tests/test_log.s"
	@echo "... tests/test_parser.o"
	@echo "... tests/test_parser.i"
	@echo "... tests/test_parser.s"
	@echo "... tests/test_random.o"
	@echo "... tests/test_random.i"
	@echo "... tests/test_random.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcpserver.o"
	@echo "... tests/test_tcpserver.i"
	@echo "... tests/test_tcpserver.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_yaml.o"
	@echo "... tests/test_yaml.i"
	@echo "... tests/test_yaml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

