logs:
  - 
      name: root
      level: unknow 
      appends:
        - StdoutLogAppender:
           level: unknow
        - FileLogAppender:
           level: unknow 
           path: ./config/log.txt
  -
      name: system
      level: unknow 
      appends:
        - StdoutLogAppender:
           level: unknow
        - FileLogAppender:
           level: unknow 
           format: '%d%T%e%T[%c]%T[%p]%T[%F:%l]%T[%t:%f]%T%m%n'
           path: ./config/systemlog.txt
time:
    format: '%Y-%m-%d %H:%M:%S'
